<!DOCTYPE html>
<html>
<head>
    <style>
        .footer {
            text-align: center;
            font-size: 12px;
            color: #04223A;
            border-top: 1px solid #04223A;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <div class="footer">
        <p>Trainee Check-in Report</p>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
        <p>Generated by: {{ auth()->user()->name }}</p>
        <p>Page {PAGE_NUM} of {PAGE_COUNT}</p>
    </div>
</body>
</html>
