<!DOCTYPE html>
<html>
<head>
    <title>Trainees Report</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Mainadra:wght@400;700&display=swap');

        body {
            font-family: 'Comfortaa', sans-serif; /* Using Comfortaa font */
            color: #04223A; /* Default text color */
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-size: 11px; /* Adjusted font size */
        }

        .page {
            page-break-after: always;
            position: relative;
            padding: 0 10mm; /* Adjusted page padding */
            margin: 0;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            position: relative;
        }

        .header img {
            width: 100px;
            height: auto;
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0.3; /* Adjust opacity */
            top: 50%;
            z-index: -1; Ensure it's behind text
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #04223A;
            position: relative;
            z-index: 1; /* Ensure text is above the logo */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 40px; /* Space before footer */
        }

        table, th, td {
            border: 1px solid #04223A; /* Theme color */
        }

        th, td {
            padding: 8px; /* Adjusted padding */
            text-align: left;
            font-size: 10px; /* Adjusted font size for table content */
        }

        th {
            background-color: #34A8FE; /* Header color */
            color: white;
        }

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px; /* Adjusted font size for footer */
            color: #04223A;
            border-top: 1px solid #04223A;
            padding: 5px 0; /* Adjusted padding */
        }

        @page {
            margin: 15mm; /* Reduced margins */
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
            }
        }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <img src="{{ public_path('images/logo.png') }}" alt="Project Logo">
            <h1>Admitted Trainees Report</h1>
        </div>

        <table>
            <thead>
                <tr>
                    <th>S/No</th>
                    <th>Name</th>
                    <th>ID No.</th>
                    <th>Phone No.</th>
                    <th>Ward</th>
                    <th>Polling Station</th>
                    <th>Role</th>
                    <th>Admitted By</th>
                </tr>
            </thead>
            <tbody>
                @foreach($trainees as $trainee)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $trainee->name }}</td>
                        <td>{{ $trainee->id_number }}</td>
                        <td>{{ $trainee->phone_number }}</td>
                        <td>{{ $trainee->ward }}</td>
                        <td>{{ $trainee->polling_station }}</td>
                        <td>{{ $trainee->role }}</td>
                        <td>{{ $trainee->admittedBy->name ?? '---' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <footer>
            <p>Trainee Check-in Report | Generated on {{ now()->format('F j, Y \a\t g:i A') }} | Generated by: {{ auth()->user()->name }}</p>
        </footer>
    </div>
</body>
</html>
